apiVersion: apps/v1
kind: Deployment
metadata:
  name: iplant-groups
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: iplant-groups
  template:
    metadata:
      labels:
        de-app: iplant-groups
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - iplant-groups
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: gpg-files
          secret:
            secretName: gpg-keys
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: iplant-groups.properties
                path: iplant-groups.properties
      containers:
      - name: iplant-groups
        image: "discoenv/iplant-groups"
        resources:
          requests:
            cpu: "160m"
            memory: "512Mi"
          limits:
            cpu: "3000m"
            memory: "2Gi"
        args:
          - --config
          - /etc/iplant/de/iplant-groups.properties
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: gpg-files
            mountPath: /etc/iplant/crypto
            readOnly: true
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
        env:
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: java-tool-options
                key: low
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: iplant-groups
spec:
  selector:
    de-app: iplant-groups
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
